apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment # you can any name here 
  labels:
    app: nginx # you can put any label as long as it is a key value pair
spec:
  replicas: 3  # define the number of cpods to deploy ( run)
  selector:
    matchLabels:
      app: nginx   # same as label
  template:
    metadata:
      labels:
        app: nginx   # same as label
    spec:
      containers:
      - name: nginx # give a container any name you want
        image: nginx:1.14.2  # put your docker image here; Don't forget the tag if needed
        ports:
        - containerPort: 80  # put the container port here
